### ISSUE TITLE
First step

### ISSUE THREAD

**Issue by aiboy** [SimplePEG/Java#1]
Prepare repository for consumption by package manager (don't publish it), create basic structure (for code and tests) and make Hello world

As far far as I know Java will work with maven

**Comment by vladimir-x** [comment]
If package manager no need to be pushed, i can build project without it

**Comment by aiboy** [comment]
@vladimir-x fine to me, but you still need to make project structure for tests, without test it will be incrementally harder to write and debug code

Meanwhile I will create issue for first code.

**Comment by aiboy** [comment]
@vladimir-x after doing this, feel free to start with #2

**Comment by vladimir-x** [comment]
I can't push my code in this repo.
Did it mean, that I need to create branch in me own account, or you give me access to push, or something another ?

**Comment by aiboy** [comment]
@vladimir-x Will it be inconvenient for you to work with pull requests? (I want to add TravisCI with tests and Coverage.io later on). Just fork repo and make pull request. Tell me if it's too much work for you.

**Comment by vladimir-x** [comment]
I think I can do it

**Comment by obenjiro** [comment]
Closed by #3
